version: '3.7'

services:
  rsp_internal_portal:
    ports:
      - 3000:3000
    image: node:10.18
    working_dir: /app
    command: /bin/bash -c 'npm i --no-optional && npm rebuild node-sass && npm run build && npm run start-dev-server'
    volumes:
        - $PWD:/app
        - $PWD/build:/app/build
    networks:
      - rsplocaldev
  cpms_localstack:
    image: localstack/localstack:latest
    container_name: rsp_localstack
    ports:
      - '4566:4566'
      - '8055:8080'
    environment:
      - SERVICES=lambda,s3,dynamodb
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
      - HOST_TMP_FOLDER=/tmp/.localstack/tmp
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_DOCKER_NETWORK=rsp-internal-portal_cpmslocaldev
      - ROOT=$PWD
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-aws/initaws:/docker-entrypoint-initaws.d"
      - "./localstack-aws/data:/usr/data"
    networks:
      - rsplocaldev

networks:
  rsplocaldev:
    driver: bridge
