service: dvsa-rsp-internal-portal

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1

functions:
  serveExpressApp:
    handler: handler.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
