name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  COPY_SOURCE: internal-portal/serveExpressApp/master.zip
  KEY_PATH: internal-portal/serveExpressApp

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: rsp-internal-portal

  promote:
    if: ${{ needs.release-please.outputs.release_created }}
    needs: release-please
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.RSP_AWS_ACCOUNT }}:role/GithubActionsRole
          role-session-name: GithubActionsSession
          aws-region: ${{ secrets.RSP_AWS_REGION }}
      - name: Upload to S3
        run: >
          aws s3api copy-object
          --tagging-directive REPLACE
          --tagging promote=YES
          --copy-source ${{ secrets.RSP_NONPROD_S3_BUCKET_NAME }}/${{ env.COPY_SOURCE }}
          --key ${{ env.KEY_PATH }}/release-${{ github.ref_name }}.zip
          --bucket ${{ secrets.RSP_NONPROD_S3_BUCKET_NAME }}